package com.bootcamp.sb.demo_sb_customer.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import com.bootcamp.sb.demo_sb_customer.entity.CustomerEntity;


// JPA + driver (postgresql)
// ! Hibernate generates the implementation class, which implements "CustomerRepository"
@Repository // Bean
public interface CustomerRepository extends JpaRepository<CustomerEntity, Long> {
    // ! During maven compilation, the implementation class is generated by Hibernate
    // save()
    // saveAll()
    // findAll()
    // findById()
    // deleteById()
}
