server:
  port: 8100

bc:
  xfin:
    service:
      url: http://ec2-54-176-81-104.us-west-1.compute.amazonaws.com:8101

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: "Asia/Hong_Kong"