server:
  port: 8101

spring.datasource:
  driverClassName: "org.postgresql.Driver"
  url: "jdbc:postgresql://localhost:5432/bc-xfin-service"
  username: "postgres"
  password: "admin1234"

spring.jpa:
  show-sql: true
  hibernate:
    ddl-auto: update
    naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.data.redis:
  host: redisserver  # Use 'redis' instead of 'localhost'
  port: 6379