server:
  port: 8101

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bc-xfin-service
    username: postgres
    password: admin1234

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          time_zone: "Asia/Hong_Kong"

  data:
    redis:
      host: redisserver
      port: 6379